import bracelet1 from "./img/bracelet1.jpg";
import bracelet2 from "./img/bracelet2.jpg";
import bracelet3 from "./img/bracelet3.jpg";
import bracelet4 from "./img/bracelet4.jpg";
import bracelet5 from "./img/bracelet5.jpg";
import bracelet6 from "./img/bracelet6.jpg";
import bracelet7 from "./img/bracelet7.jpg";
import bracelet8 from "./img/bracelet8.jpg";
import bracelet9 from "./img/bracelet9.jpg";
import bracelet10 from "./img/bracelet10.jpg";
import bracelet11 from "./img/bracelet11.jpg";
import bracelet12 from "./img/bracelet12.jpg";
import bracelet13 from "./img/bracelet13.jpg";
import bracelet14 from "./img/bracelet14.jpg";
import bracelet15 from "./img/bracelet15.jpg";
import bracelet16 from "./img/bracelet16.jpg";
import bracelet17 from "./img/bracelet17.jpg";
import bracelet18 from "./img/bracelet18.jpg";
import bracelet19 from "./img/bracelet19.jpg";
import bracelet20 from "./img/bracelet20.jpg";
import bracelet21 from "./img/bracelet21.jpg";
import bracelet22 from "./img/bracelet22.jpg";
import bracelet23 from "./img/bracelet23.jpg";
import bracelet24 from "./img/bracelet24.jpg";
import bracelet25 from "./img/bracelet25.jpg";
import bracelet26 from "./img/bracelet26.jpg";
import bracelet27 from "./img/bracelet27.jpg";
import bracelet28 from "./img/bracelet28.jpg";
import bracelet29 from "./img/bracelet29.jpg";
import bracelet30 from "./img/bracelet30.jpg";
import bracelet31 from "./img/bracelet31.jpg";
import bracelet32 from "./img/bracelet32.jpg";
import bracelet33 from "./img/bracelet33.jpg";
import bracelet34 from "./img/bracelet34.jpg";
import bracelet35 from "./img/bracelet35.jpg";

const sampleVideo =
  "https://cdn.pixabay.com/video/2016/06/18/3501-171376186_large.mp4";

const braceletsdata = [
  {
    id: 1,
    name: "Dally Wear Kadli",
    description: "Trendy Dally Wear traditional motifs",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet1, bracelet2],
    videos: [sampleVideo],
    badge: "NEW",
    deliveryCharge: 1500,
    size: 14,
  },
  {
    id: 2,
    name: "AD Dally Wear Kadli",
    description: "Premium AD Dally Wear craftsmanship",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet2],
    videos: [sampleVideo],
    deliveryCharge: "Free",
    size: 15,
  },
  {
    id: 3,
    name: "Dally Wear Kadli",
    description: "Lightweight stylish Dally Wear bracelet",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet3],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 15,
  },
  {
    id: 4,
    name: "Dally Wear",
    description: "Elegant daily wear silver motifs",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet4],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 13,
  },
  {
    id: 5,
    name: "AD Dally Wear Kadli",
    description: "Premium AD craftsmanship bracelet",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet5],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14,
  },
  {
    id: 6,
    name: "Dally Wear Kadli",
    description: "Trendy Dally Wear traditional motifs",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet6],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14,
  },
  {
    id: 7,
    name: "AD Kadli",
    description: "Premium AD daily wear design",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet7],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 15,
  },
  {
    id: 8,
    name: "Dally Wear",
    description: "Stylish and lightweight bracelet",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet8],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 16,
  },
  {
    id: 9,
    name: "Dally Wear Kadli",
    description: "Elegant daily wear silver motifs",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet9],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 13,
  },
  {
    id: 10,
    name: "AD Dally Wear Kadli",
    description: "Premium AD Dally Wear craftsmanship",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet10],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14,
  },
  {
    id: 11,
    name: "Dally Wear",
    description: "Trendy silver bracelet for daily wear",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet11],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 15,
  },
  {
    id: 12,
    name: "AD Kadli",
    description: "Premium AD design with elegance",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet12],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 15,
  },
  {
    id: 13,
    name: "Dally Wear Kadli",
    description: "Stylish Dally Wear bracelet for everyday use",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet13],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 15,
  },
  {
    id: 14,
    name: "AD Dally Wear Kadli",
    description: "Premium AD Dally Wear design",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet14],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14,
  },
  {
    id: 15,
    name: "Dally Wear",
    description: "Elegant and lightweight daily bracelet",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet15],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 13,
  },
  {
    id: 16,
    name: "AD Dally Wear Kadli",
    description: "Premium craftsmanship bracelet",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet16],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 17,
  },
  {
    id: 17,
    name: "Dally Wear Kadli",
    description: "Trendy Dally Wear traditional motifs",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet17],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 15,
  },
  {
    id: 18,
    name: "AD Kadli",
    description: "Elegant AD bracelet for daily wear",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet18],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14,
  },
  {
    id: 19,
    name: "Dally Wear",
    description: "Lightweight and stylish silver bracelet",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet19],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14.5,
  },
  {
    id: 20,
    name: "AD Dally Wear Kadli",
    description: "Premium AD daily wear design",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet20],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 15,
  },
  {
    id: 21,
    name: "Dally Wear Kadli",
    description: "Elegant silver motifs for daily wear",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet21],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14,
  },
  {
    id: 22,
    name: "AD Kadli",
    description: "Premium AD crafted bracelet",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet22],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 15,
  },
  {
    id: 23,
    name: "Dally Wear",
    description: "Trendy silver bracelet for daily use",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet23],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 15,
  },
  {
    id: 24,
    name: "AD Dally Wear Kadli",
    description: "Premium AD Dally Wear craftsmanship",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet24],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14,
  },
  {
    id: 25,
    name: "Dally Wear Kadli",
    description: "Elegant daily wear bracelet with motifs",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet25],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14.5,
  },
  {
    id: 26,
    name: "AD Kadli",
    description: "Premium AD design for daily wear",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet26],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14,
  },
  {
    id: 27,
    name: "Dally Wear",
    description: "Stylish lightweight bracelet for daily use",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet27],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 16,
  },
  {
    id: 28,
    name: "AD Dally Wear Kadli",
    description: "Premium AD daily wear silver bracelet",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet28],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14,
  },
  {
    id: 29,
    name: "Dally Wear Kadli",
    description: "Elegant daily wear silver motifs",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet29],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 15,
  },
  {
    id: 30,
    name: "AD Kadli",
    description: "Premium AD craftsmanship bracelet",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet30],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 15,
  },
  {
    id: 31,
    name: "Dally Wear",
    description: "Trendy daily wear bracelet",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet31],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14,
  },
  {
    id: 32,
    name: "AD Dally Wear Kadli",
    description: "Premium AD daily wear design",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet32],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14,
  },
  {
    id: 33,
    name: "Dally Wear Kadli",
    description: "Elegant silver motifs for daily use",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet33],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14,
  },
  {
    id: 34,
    name: "AD Kadli",
    description: "Premium AD daily wear bracelet",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet34],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 17,
  },
  {
    id: 35,
    name: "Dally Wear",
    description: "Stylish and lightweight silver bracelet",
    price: 1300,
    discountPrice: 650,
    category: "bracelets",
    material: "silver",
    images: [bracelet35],
    videos: [sampleVideo],
    deliveryCharge: 0,
    size: 14,
  },
];

export default braceletsdata;
