const Ankletdata = [
  {
    id: 1,
    name: "Twist Chain Anklet",
    description: "Elegant anklet with timeless design",
    price: 15000,
    discountPrice: 13000,
    category: "anklets",
    material: "gold",
    deliveryCharge: 0,
    images: [
      "https://images.pexels.com/photos/7068000/pexels-photo-7068000.jpeg",
      "https://images.pexels.com/photos/7068000/pexels-photo-7068000.jpeg",
    ],
    videos: [
      "https://www.w3schools.com/html/mov_bbb.mp4", // sample video
    ],
    badge: "NEW",
    size: 20,
  },
  {
    id: 2,
    name: "Pearl Beads Anklet",
    description: "Elegant anklet with timeless design",
    price: 15000,
    discountPrice: 13000,
    category: "anklets",
    material: "pearl",
    deliveryCharge: 0,
    images: [
      "https://images.pexels.com/photos/7068000/pexels-photo-7068000.jpeg",
      "https://images.pexels.com/photos/7068000/pexels-photo-7068000.jpeg",
    ],
    videos: [
      "https://www.w3schools.com/html/movie.mp4", // sample video
    ],
    size: 20,
  },
  {
    id: 3,
    name: "Charm Anklet",
    description: "Elegant anklet with timeless design",
    price: 10000,
    discountPrice: 9000,
    category: "anklets",
    material: "silver",
    deliveryCharge: 0,
    images: [
      "https://images.pexels.com/photos/7068000/pexels-photo-7068000.jpeg",
    ],
    videos: [],
    size: 20,
  },
  {
    id: 4,
    name: "Twisted Rope Anklet",
    description: "Elegant anklet with timeless design",
    price: 13000,
    discountPrice: 11000,
    category: "anklets",
    material: "platinum",
    deliveryCharge: 0,
    images: [
      "https://images.pexels.com/photos/7068000/pexels-photo-7068000.jpeg",
    ],
    videos: [],
    size: 20,
  },
  {
    id: 5,
    name: "Floral Pattern Anklet",
    description: "Elegant anklet with timeless design",
    price: 18000,
    discountPrice: 15000,
    category: "anklets",
    material: "silver",
    deliveryCharge: 0,
    images: [
      "https://images.pexels.com/photos/7068000/pexels-photo-7068000.jpeg",
    ],
    videos: [],
    size: 20,
    badge: "SALE",
  },
  {
    id: 6,
    name: "Leather Strap Anklet",
    description: "Elegant anklet with timeless design",
    price: 8000,
    discountPrice: 4000,
    category: "anklets",
    material: "leather",
    deliveryCharge: 0,
    images: [
      "https://images.pexels.com/photos/7068000/pexels-photo-7068000.jpeg",
    ],
    videos: [],
    size: 4,
  },
  {
    id: 7,
    name: "Ruby Stone Anklet",
    description: "Elegant anklet with timeless design",
    price: 20000,
    discountPrice: 17000,
    category: "anklets",
    material: "ruby",
    deliveryCharge: 0,
    images: [
      "https://images.pexels.com/photos/7068000/pexels-photo-7068000.jpeg",
    ],
    videos: [],
    size: 20,
  },
  {
    id: 8,
    name: "Emerald Stone Anklet",
    description: "Elegant anklet with timeless design",
    price: 22000,
    discountPrice: 18000,
    category: "anklets",
    material: "emerald",
    deliveryCharge: 0,
    images: [
      "https://images.pexels.com/photos/7068000/pexels-photo-7068000.jpeg",
    ],
    videos: [],
    size: 20,
  },
];

export default Ankletdata;
