name: Deploy Frontend Docker Image

on:
  push:
    branches: [ production ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  create:


env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/avishjewels-frontend

jobs:
  build-and-deploy:
    name: Build Frontend (${{ github.ref == 'refs/heads/production' && 'Production' || 'Development' }})
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'create' && github.ref == 'refs/heads/production')
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check deployment environment
      run: |
        echo "Branch: ${{ github.ref }}"
        echo "Event: ${{ github.event_name }}"
        if [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
          echo "🚀 This is a PRODUCTION deployment - Docker image will be built and pushed"
        else
          echo "🔧 This is a development build - Docker image will be built but NOT pushed"
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/production'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: ${{ github.ref == 'refs/heads/production' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          REACT_APP_API_URL=https://api.avishjewels.com/api/v1
          REACT_APP_ENV=production

